### ISSUE TITLE
Make Chocolatey package trusted

### ISSUE THREAD

**Issue by jakublevy** [kiedtl/winfetch#101]
By default, every version of a package on Chocolatey has to undergo a moderation process that can take even more than 1 month. Unmoderated packages cannot be installed without passing the version explicitly to `choco install`. 

winfetch 2.1.0 was pushed on Chocolatey on June 19, 2021 and it is still not moderated.

There are also [trusted packages on Chocolatey](https://docs.chocolatey.org/en-us/faqs#what-is-a-trusted-package), that bypass human moderation checks. They are packages that either have a long and good history or come from official sources (developers). I guess since the Chocolatey installation method is on the wiki - it can be considered official.

If developers and maintainers @kiedtl, @rashil2000, @jcwillox agree, I will contact Chocolatey moderators about making winfetch package as a trusted with this issue as a proof.

**Comment by rashil2000** [comment]
That's a very good idea. We would definitely want this. I'm not at all familiar with chocolatey's processes so I still have a lot to learn. What stuff is required to convince them that we can be trusted?

**Comment by jakublevy** [comment]
Well, I don't have a trusted package, so I haven't actually gone through that process, and there is no recommended procedure. 
But I think a package maintainer has to contact Chocolatey moderators requesting the conversion to a trusted package with some kind of proof that he/she is a trusted person.

The proof can IMO be just this issue (my GitHub account is connected with my Chocolatey account, so the OP can be verified). But I am just a package maintainer, neither an author nor contributor (at least yet), so I guess I need a "word of approval" by the actual developers or the least their acknowledgment of this here in this issue.

**Comment by rashil2000** [comment]
Well, in that case, @kiedtl would be the right person to ask...

**Comment by kiedtl** [comment]
> I guess I need a "word of approval" by the actual developers or at least their acknowledgment of this here in this issue.

I think either @rashil2000 or @jcwillox can furnish that, being the de facto developers of this project. However, I, the official Winfetch maintainer in name only, can give that approval should the Chocolatey devs descend too deep into a well of unmitigated pedantry. :^)))

**Comment by jakublevy** [comment]
I have contacted Chocolatey moderators about converting winfetch package to a trusted one.
I will let you know when I receive a response.

**Comment by rashil2000** [comment]
Great, thanks for the awesome work @jakublevy !!!

**Comment by flcdrg** [comment]
Hi folks, 

I'm a volunteer moderator for Chocolatey. Just to clarify that being marked 'trusted' usually takes roughly 3 versions of a package to be approved. It might depend a little on which moderator you get, but usually around by that point we've got enough confidence that the package is doing the right things and we don't think we'll need to manually approve future versions.

David

**Comment by rashil2000** [comment]
Hey @flcdrg!

Thanks for your input! 
We already have 3 releases in pushed to Chocolatey, the latest being a month ago (and it was updated some days ago to address a bug #99). There haven't been many changes since, but if required I can make a new release incorporating #96 and #97. Would that be fine?

**Comment by flcdrg** [comment]
I've just added comments to your two pending versions. You're going to have to reconsider how the package installs. Unfortunately this wasn't picked up in the moderation of the first version you submitted.

**Comment by rashil2000** [comment]
I saw the comments.

If I remember correctly, we were using something similar to shimming that lead to #99. I'm not sure there's any other way than either creating a custom batch file or adding the ps1 scripts directly to choco's bin directory. We will lose the both the correct version reporting and the argument completion if we create shims. #99 has some more details regarding this.

**Comment by jakublevy** [comment]
So, the rewritten installer got rejected because it puts winfetch.ps1 directly into Chocolatey bin directory.
This correct way is to use [Install-ChocolateyPowershellCommand](https://docs.chocolatey.org/en-us/create/functions/install-chocolateypowershellcommand#mainContent) which puts batch redirect in to Chocolatey bin. 

The problem is that this is the [Install-ChocolateyPowershellCommand](https://docs.chocolatey.org/en-us/create/functions/install-chocolateypowershellcommand#mainContent) is not really good as I explained in [here](https://github.com/kiedtl/winfetch/issues/99#issuecomment-895282523).

This results in lost tab completion and execution always only by `powershell`.

I don't know what to do, the only thing I can do is to go back to the former winfetch installer which uses fancy Chocolatey functions, but this way, it simply is not that good as installation from PSGallery.

**Comment by jakublevy** [comment]
Well, I think there is one more way that could get through Chocolatey moderation.

I can put winfetch.ps1 into `"$env:ChocolateyToolsLocation\winfetch"` and add `"$env:ChocolateyToolsLocation\winfetch"` into PATH environment variable ($env:ChocolateyToolsLocation is generally "C:\tools").

This way I would not touch `"$env:ChocolateyInstall\bin"` which seems to be forbidden to do so without Chocolatey built-in functions (which just does not work in our case).

**Comment by jakublevy** [comment]
So I re-pushed version 2.1.0 and 2.2.0 as described in the previous comment. 
If this fails, I will unfortunately have to go back to [Install-ChocolateyPowershellCommand](https://docs.chocolatey.org/en-us/create/functions/install-chocolateypowershellcommand).

I will let you know after I get a response.

**Comment by flcdrg** [comment]
Just following up that it might be worth posting to either https://groups.google.com/g/chocolatey or https://gitter.im/chocolatey/choco to find out the best way to deal with the shimming.

**Comment by jakublevy** [comment]
So we've finally got winfetch [2.1.0](https://community.chocolatey.org/packages/winfetch/2.1.0) and [2.2.0](https://community.chocolatey.org/packages/winfetch/2.2.0) packages approved.
The package is not trusted yet, but future updates should be seamless, so we will probably get trusted status soon (possibly after few updates).

**Comment by rashil2000** [comment]
Hey @jakublevy :)

Thank you for the update!

**Comment by rashil2000** [comment]
Hey @jakublevy !
We just released a new version, is there anything pending on this thread? If not, I will close this along with #99 
Thanks!

**Comment by jakublevy** [comment]
Hi, @rashil2000 
honestly, from my experience of getting a few packages coincidentally trusted recently, there is really not much you can do about it. The best thing is to release versions more often and then the moderators will get sick of manually checking "the same" packages every time.

This issue is therefore pointless and can be closed.

**Comment by rashil2000** [comment]
Okay, thanks for the quick reply!
