### ISSUE TITLE
Winfetch shows wrong shell

### ISSUE THREAD

**Issue by kamack38** [kiedtl/winfetch#102]
Even though I have PowerShell core 7.1.3 it shows I have PowerShell  v5.1.19041.1023

![Picture 1](https://user-images.githubusercontent.com/64226248/129251441-315e7ae8-6973-417c-8e72-9ed824b700f6.png)
![Picrure 2](https://user-images.githubusercontent.com/64226248/129251523-ae0818ef-0c14-47f6-923c-0c27eda5849c.png)

**Comment by rashil2000** [comment]
Did you install it using choco?

**Comment by kamack38** [comment]
Yes, I installed it using choco. Is there any problem with that?

**Comment by jakublevy** [comment]
Please see #99.

The problem is already solved in Chocolatey package for version 2.2.0, but this version is currently not moderated by Chocolatey moderators yet.

Update using `choco upgrade winfetch --version 2.2.0`

**Comment by kamack38** [comment]
Thanks, it solved my porblem.
