### ISSUE TITLE
Overclocked CPU speed

### ISSUE THREAD

**Issue by sashaaaaaaaaa** [kiedtl/winfetch#106]
Would be cool if winfetch showed your overclocked CPU speed instead of the stock one. Or both.

**Comment by rashil2000** [comment]
I'm not much familiar with what overclocked speed here means. 
When you say that you want to see overclocked speed, does it mean that:
- Your CPU can achieve higher frequencies during execution of some programs, compared to the advertised frequency, and you want winfetch to report that real-time frequency, or
- The maximum frequency, as the Task Manager reports, increases when you overclock, and you want to see that

**Comment by MainEditor** [comment]
[winfetch.zip](https://github.com/kiedtl/winfetch/files/9276310/winfetch.zip)
I'm not an PowerShell expert but added some feature. But it reduce performance(maybe because pwsh slow on string concatenation. I'm also tried use string builder but don't saw any improvements). And I'm don't tested it on other CPU's. Only on my ancient I7-860 which I overclocked to 3.61Ghz

**Comment by rashil2000** [comment]
What is the output of the following command on your PC?
`Get-CimInstance Win32_Processor | Format-List *`

**Comment by MainEditor** [comment]
`Availability                            : 3
CpuStatus                               : 1
CurrentVoltage                          : 10
DeviceID                                : CPU0
ErrorCleared                            :
ErrorDescription                        :
LastErrorCode                           :
LoadPercentage                          : 6
Status                                  : OK
StatusInfo                              : 3
AddressWidth                            : 64
DataWidth                               : 64
ExtClock                                : 180
L2CacheSize                             : 1024
L2CacheSpeed                            :
MaxClockSpeed                           : 3611
PowerManagementSupported                : False
ProcessorType                           : 3
Revision                                : 7685
SocketDesignation                       : LGA1156
Version                                 :
VoltageCaps                             :
Caption                                 : Intel64 Family 6 Model 30 Stepping 5
Description                             : Intel64 Family 6 Model 30 Stepping 5
InstallDate                             :
Name                                    : Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
ConfigManagerErrorCode                  :
ConfigManagerUserConfig                 :
CreationClassName                       : Win32_Processor
PNPDeviceID                             :
PowerManagementCapabilities             :
SystemCreationClassName                 : Win32_ComputerSystem
SystemName                              : DESKTOP-I8BCFN9
CurrentClockSpeed                       : 3611
Family                                  : 198
OtherFamilyDescription                  :
Role                                    : CPU
Stepping                                :
UniqueId                                :
UpgradeMethod                           : 1
Architecture                            : 9
AssetTag                                : To Be Filled By O.E.M.
Characteristics                         : 4
L3CacheSize                             : 8192
L3CacheSpeed                            : 0
Level                                   : 6
Manufacturer                            : GenuineIntel
NumberOfCores                           : 4
NumberOfEnabledCore                     : 4
NumberOfLogicalProcessors               : 8
PartNumber                              : To Be Filled By O.E.M.
ProcessorId                             : BFEBFBFF000106E5
SecondLevelAddressTranslationExtensions : True
SerialNumber                            : To Be Filled By O.E.M.
ThreadCount                             : 8
VirtualizationFirmwareEnabled           : True
VMMonitorModeExtensions                 : True
PSComputerName                          :
CimClass                                : root/cimv2:Win32_Processor
CimInstanceProperties                   : {Caption, Description, InstallDate, Name…}
CimSystemProperties                     : Microsoft.Management.Infrastructure.CimSystemProperties`
Just outputs info about my CPU

**Comment by MainEditor** [comment]
Do you wanna add show CPU clock speed in winfetch but of course more advanced for work on AMD CPUs?

**Comment by rashil2000** [comment]
Can you check the linked PR if it works for you?

**Comment by MainEditor** [comment]
Works fine

**Comment by rashil2000** [comment]
Done. Can you check now?

**Comment by MainEditor** [comment]
Great job it's works perfectly and blazingly fast to compare with my implementation. I'm also saw your code and compared with mine and I'm understood why my code was slowly. Is that because I'm call CPU information twice for get it's frequency and it's name and use Substring method with concatenation of strings via writing «$string0 + $string1»?

**Comment by rashil2000** [comment]
When you use `Get-CimInstance`, you should specify what properties you want, i.e. name and frequency. If you don't, it will fetch everything and hence take a lot of time.

String concatenation has no effect here.

**Comment by MainEditor** [comment]
Oh OK. Thanks!

**Comment by MainEditor** [comment]
Is that changes will be released as new point release version?

**Comment by rashil2000** [comment]
Yes

**Comment by MainEditor** [comment]
OK I'll wait when new release will be available in scoop package manager. Good that issue has closed. Goodbye
