### ISSUE TITLE
Can't run winfetch PS1 script

### ISSUE THREAD

**Issue by dathckr** [kiedtl/winfetch#108]
I downloaded winfetch powershell script and try to run. And powershell give me an error
PS C:\Users\dathckr> .\winfetch.ps1
ParserError: C:\Users\dathckr\winfetch.ps1:226
Line |
 226 |  </button>        </div>
     |                   ~
     | The '<' operator is reserved for future use.
My Powershell version is : 
PS C:\Users\dathckr> pwsh --version
PowerShell 7.1.4
I'm using Windows 11 Insider Preview. What is the problem?
P/s: I tried another version (Powershell 6), and not only one error :)
At C:\Users\dathckr\winfetch.ps1:214 char:21
+                 Sign&nbsp;up
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\dathckr\winfetch.ps1:226 char:18
+ </button>        </div>
+                  ~
The '<' operator is reserved for future use.
At C:\Users\dathckr\winfetch.ps1:240 char:16
+ </button>      </div>
+                ~
The '<' operator is reserved for future use.
At C:\Users\dathckr\winfetch.ps1:253 char:189
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Users\dathckr\winfetch.ps1:253 char:269
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\dathckr\winfetch.ps1:257 char:167
+ ... ck Link--secondary no-underline f5 Bump-link--hover">Mobile <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Users\dathckr\winfetch.ps1:257 char:247
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\dathckr\winfetch.ps1:258 char:178
+ ... k Link--secondary no-underline f5 Bump-link--hover">Actions <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\Users\dathckr\winfetch.ps1:258 char:258
+ ... nk-symbol float-right text-normal color-text-tertiary pr-3">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\dathckr\winfetch.ps1:259 char:184
+ ... ink--secondary no-underline f5 Bump-link--hover">Codespaces <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed
and run as administator the error is still here.

**Comment by rashil2000** [comment]
How did you download it? It looks like the entire script is getting stored in a single line. Can you open the script in Notepad and confirm that?

Make sure the script looks exactly like this when you open Notepad - https://raw.githubusercontent.com/kiedtl/winfetch/master/winfetch.ps1

(you can copy-paste from here if it doesn't)
