### ISSUE TITLE
Colored version broken on Windows 7

### ISSUE THREAD

**Issue by AnonimFan** [kiedtl/winfetch#110]
So, last night I found this thing, installed it, and tried the /c switch. Well, its broken:
![image](https://user-images.githubusercontent.com/70202298/136697311-52fc3a83-9522-45c2-8461-a8d226ee4c8d.png)

This is the non-colored version, not broken at all:
![image](https://user-images.githubusercontent.com/70202298/136697334-bb26afd2-835b-459e-8b7f-31a6de34c43f.png)

**Comment by AnonimFan** [comment]
Update:
I installed Powershell5.1 and ran the PS version, but all i get is this:
![image](https://user-images.githubusercontent.com/70202298/136699071-cfba8dff-c776-4999-a72d-9e20e3293c1e.png)

**Comment by rashil2000** [comment]
You will need to enable ANSI support to see colors properly - https://github.com/kiedtl/winfetch/wiki/ANSI-Colors

Please search for similar issues before opening a new one.
