### ISSUE TITLE
Scoop reports that winfetch's manifest has been removed

### ISSUE THREAD

**Issue by AwesomeCronk** [kiedtl/winfetch#112]
I got the notification email that there was a new release of Winfetch made today, so I opened a terminal and tried to update it through scoop. Well, long story short I wound up running `scoop status` and got this:
![image](https://user-images.githubusercontent.com/55630616/140623610-b383cdc7-37e8-46ea-b79f-b07e30b0f853.png)

Has the manifest been removed intentionally?

**Comment by jcwillox** [comment]
Yeah, @rashil2000 had it moved to the main bucket, I just noticed as well, I'll update the release notes to mention this. Should be fine if you just reinstall it.

```pwsh
scoop uninstall winfetch
scoop install winfetch
```

**Comment by tonyping** [comment]
Merged! [2899](https://github.com/ScoopInstaller/Main/pull/2899)

**Comment by jcwillox** [comment]
Do we know why the manifest didn't auto-update?

**Comment by rashil2000** [comment]
Scoop updates in Main and Extras buckets now happen at half the frequency as before, because one of the two maintainers whose pipelines pushed updates withdrew his support. 

We are working on this - https://github.com/ScoopInstaller/Main/pull/2871 - but it might be a while.

**Comment by AwesomeCronk** [comment]
Yeah scoop/main is a bit of a mess right now...
Thanks for letting me know what's going on!

**Comment by jcwillox** [comment]
Oh how unfortunate, so there's like up to a 2-day delay now?

**Comment by rashil2000** [comment]
Possibly, we can't really predict
