### ISSUE TITLE
Color of the info has changed

### ISSUE THREAD

**Issue by kamack38** [kiedtl/winfetch#113]
Why did the color of the info changed?
I've just formatted my PC, and now I have a different color of the info. (Now, it's yellow) How can I make it blue again?
![obraz](https://user-images.githubusercontent.com/64226248/141682827-622b354c-9a45-4b13-99b7-cc9c5124c0f5.png)
![obraz](https://user-images.githubusercontent.com/64226248/141682848-6b02b396-2a02-4c98-a06b-fa1202c92a18.png)

OS: Windows 10
Terminal : Windows Terminal Preview (the latest version)
Shell: PowerShell `v7,20`

**Comment by rashil2000** [comment]
#97
