### ISSUE TITLE
Suggestion: Show hidden packages

### ISSUE THREAD

**Issue by HashemLovesYou** [kiedtl/winfetch#114]
add `-force` to line 831: 
`$scooppkg = (Get-ChildItem -Force -Path $scoopdir -Directory).Count - 1`
so it will show the correct package count even if the `scoop/apps` folder or subfolders are hidden

**Comment by rashil2000** [comment]
Where is your scoop folder located? 

Even if your top-level scoop folder is hidden, `Get-ChildItem $scoopdir` will show all the folders correctly. `-Force` is not required.

**Comment by HashemLovesYou** [comment]
`c:\users\[user]\`
it's because all of the subfolders were hidden as well

**Comment by rashil2000** [comment]
Paste the output of the following two commands: `scoop list` and `Get-ChildItem -Path c:\users\[user]\scoop\apps -Directory`

**Comment by HashemLovesYou** [comment]
### With `scoop` subfolders hidden:
```
> scoop list
scoop: 'list' isn't a scoop command. See 'scoop help'.
```
the other returns nothing

### With `scoop` subfolders unhidden:
```
> scoop list
Installed apps:

  winfetch 2.3.0 [main]

> Get-ChildItem -Path c:\users\yehud\scoop\apps -Directory

    Directory: C:\Users\yehud\scoop\apps

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          11/16/2021 11:05 PM                scoop
d----          11/16/2021 11:05 PM                winfetch
```

**Comment by rashil2000** [comment]
This is expected behaviour. 

Scoop also internally uses Get-ChildItem and related commands - if `scoop list` doesn't display anything, neither should Winfetch.
