### ISSUE TITLE
[Bug]: can't read config when config file is `SymbolicLink`

### ISSUE THREAD

**Issue by younger-1** [kiedtl/winfetch#125]
I moved the config file of winfetch to dotfiles manager and leave the origin config path a symboliclink.

```ps1
➜  (Get-item ~\.config\winfetch\config.ps1).LinkType
SymbolicLink
```

Now everytime I run winfetch it ignore my configuration and rewrite the symboliclink with default configuration.

```log
Missing config: Saved default config to 'C:\Users\younger\.config\winfetch\config.ps1'.
```

**Comment by rashil2000** [comment]
PowerShell 5.1 or 7.1?

**Comment by younger-1** [comment]
PowerShell 7.1. I tryed in PowerShell 5.1 too and it still cause problem

**Comment by rashil2000** [comment]
Fixed

**Comment by younger-1** [comment]
Thanks
