### ISSUE TITLE
How can I change the image.png?

### ISSUE THREAD

**Issue by hungpham3112** [kiedtl/winfetch#128]
I have the .`png` file in the same directory with `config file`, here is my config:

```
# ===== WINFETCH CONFIGURATION =====

 $image = "~/.config/winfetch/image.png"
# $noimage = $true

# Set the version of Windows to derive the logo from.
 $logo = "Windows 11"

# Make the logo blink
 $blink = $true

# Display all built-in info segments.
 $all = $true

# Add a custom info line
# function info_custom_time {
#     return @{
#         title = "Time"
#         content = (Get-Date)
#     }
# }

# Configure which disks are shown
# $ShowDisks = @("C:", "D:")
# Show all available disks
 $ShowDisks = @("*")

# Configure which package managers are shown
# disabling unused ones will improve speed
 $ShowPkgs = @("scoop")

# Use the following option to specify custom package managers.
# Create a function with that name as suffix, and which returns
# the number of packages. Two examples are shown here:
# $CustomPkgs = @("cargo", "just-install")
# function info_pkg_cargo {
#     return (cargo install --list | Where-Object {$_ -like "*:" }).Length
# }
# function info_pkg_just-install {
#     return (just-install list).Length
# }

# Configure how to show info for levels
# Default is for text only.
# 'bar' is for bar only.
# 'textbar' is for text + bar.
# 'bartext' is for bar + text.
# $cpustyle = 'bar'
 $memorystyle = 'textbar'
# $diskstyle = 'bartext'
# $batterystyle = 'bartext'


# Remove the '#' from any of the lines in
# the following to **enable** their output.

@(
    "title"
    "dashes"
    "os"
    "computer"
    "kernel"
    "motherboard"
    # "custom_time"  # use custom info line
    "uptime"
    # "ps_pkgs"  # takes some time
    "pkgs"
    "pwsh"
    "resolution"
    "terminal"
    "theme"
    "cpu"
    "gpu"
    "cpu_usage"  # takes some time
    "memory"
    "disk"
    # "battery"
    # "locale"
    # "weather"
    # "local_ip"
    # "public_ip"
    "blank"
    "colorbar"
)
```

After change `$image` I got error:

![image](https://user-images.githubusercontent.com/75968004/153117905-6a40d3cd-2a78-4e4a-a394-6e5864ee061c.png)

How to change the image in right way?

**Comment by rashil2000** [comment]
```pwsh
$image = "C:\Users\hungpham\.config\winfetch\image.png"
```

**Comment by hungpham3112** [comment]
![image](https://user-images.githubusercontent.com/75968004/153120764-574c2029-92ba-4a95-b2ee-cbbc350deaad.png)

Sorry but I want to ask the way change logo more beautiful like this:
![image](https://user-images.githubusercontent.com/75968004/153120827-55e18951-3c69-49ae-baae-cace2c1dd68e.png)

**Comment by rashil2000** [comment]
You need to customize your terminal for that. For example, refer to this: https://docs.microsoft.com/en-us/windows/terminal/custom-terminal-gallery/custom-schemes#frosted-glass

**Comment by hungpham3112** [comment]
No I mean the logo, the image, 

From this:

![image](https://user-images.githubusercontent.com/75968004/153122241-2acf8818-62c6-46c8-89dd-1ce2a9f10ee5.png)


To this:
![image](https://user-images.githubusercontent.com/75968004/153122264-61bc1e82-46f6-475c-9045-31cfd3feba45.png)


Because I think the first quite ugly

**Comment by rashil2000** [comment]
```pwsh
$logo = "Windows 10"
```

**Comment by hungpham3112** [comment]
> ```powershell
> $logo = "Windows 10"
> ```

Every time I clear the screen or have a long list of command, winfetch will disappear from buffer. Is there way to make winfetch always show in terminal?

**Comment by rashil2000** [comment]
```pwsh
function clear { Clear-Host; winfetch }
```

**Comment by hungpham3112** [comment]
config.ps1
```
winfetch
# set PowerShell to UTF-8
[console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding

Import-Module posh-git
Import-Module oh-my-posh
$omp_config = Join-Path $PSScriptRoot "night-owl.omp.json"
oh-my-posh --init --shell pwsh --config $omp_config | Invoke-Expression

Import-Module -Name Terminal-Icons

# PSReadLine
Set-PSReadLineOption -EditMode Emacs
Set-PSReadLineOption -BellStyle None
Set-PSReadLineKeyHandler -Chord 'Ctrl+d' -Function DeleteChar
Set-PSReadLineOption -PredictionSource History

# Env
$env:GIT_SSH = "C:\Windows\system32\OpenSSH\ssh.exe"

# Alias
Set-Alias ll ls
Set-Alias g git
Set-Alias grep findstr

# Utilities
function which ($command) {
  Get-Command -Name $command -ErrorAction SilentlyContinue |
    Select-Object -ExpandProperty Path -ErrorAction SilentlyContinue
}

function clear { Clear-Host | winfetch }
```

It didn't work

**Comment by rashil2000** [comment]
Then declare the same function again with the name 'cls'

**Comment by hungpham3112** [comment]
> Then declare the same function again with the name 'cls'

Your function give to me doesn't work

**Comment by rashil2000** [comment]
You need to enter the command `clear` or `cls` after declaring the function. It will not run automatically. 

What error do you get? Can you paste a video recording here?

**Comment by hungpham3112** [comment]
![bandicam 2022-02-09 12-22-38-403](https://user-images.githubusercontent.com/75968004/153127174-0e118f2e-5664-433d-b372-ea7f17f4767f.gif)

**Comment by rashil2000** [comment]
Okay, I think I understand what's going on.

Put this command in the end:
```pwsh
Remove-Item Alias:cls, Alias:clear
```

And see if this works.

**Comment by hungpham3112** [comment]
> Okay, I think I understand what's going on.
> 
> Put this command in the end:
> 
> ```powershell
> Remove-Item Alias:cls, Alias:clear
> ```
> 
> And see if this works.

It's work, thanks a lot.
