### ISSUE TITLE
Add ability to change "-" char of the line that separates hostname from other info

### ISSUE THREAD

**Issue by ErykDarnowski** [kiedtl/winfetch#132]
Basically I'd like to add a variable to the config file that let's the user set above mentioned char. This is something that neofetch let's you do and I think it'd be a good addition to winfetch.

![screenshot](https://user-images.githubusercontent.com/81530705/155510997-8e1cf16f-3235-4dbe-abd0-81b062942a6e.png)

Let me know if this aligns your plan for winfetch!
(BTW this is my first contribution to a github project not owned by me so I may need some help)

**Comment by rashil2000** [comment]
Hmm, may I know your use case for this? 

It's definitely possible, but too much customization options will slow down winfetch.

**Comment by ErykDarnowski** [comment]
Well essentially it's only customization but I don't think it would slow winfetch down, I'd love to measure the difference but unfortunately I'm getting an unexptected token error when I try to run the file cloned from github. Do you know what may be the cause of that?

**Comment by ErykDarnowski** [comment]
Ohh I understand what you mean, in this case I'm ok with not adding this. But this is the error I'm getting:
![error](https://user-images.githubusercontent.com/81530705/155522148-58ecb5dc-4d85-4af1-ae5a-4214afaf3948.png)

**Comment by ErykDarnowski** [comment]
I'd like to get these errors resolved cause I also wanted to have a crack at adding another feature (the ability to display monitors refresh rate).

**Comment by rashil2000** [comment]
This is a bug in Windows PowerShell, that can be caused in certain regions/languages. PowerShell 7+ solves this. 

A workaround can be to use pure ASCII characters instead of Unicode symbols for drawing the boxes in these lines: https://github.com/kiedtl/winfetch/blob/f759d8b3e74e9bb2eecc0734d5c3ed2b5cfb93a3/winfetch.ps1#L462-L469

Would you like to work on this? (it's a good first issue).

**Comment by ErykDarnowski** [comment]
Ok, I've prepared this ASCII replacement does it look ok?
![ASCII](https://user-images.githubusercontent.com/81530705/155529746-219dcfdc-0199-4740-938d-2aadff24e323.png)

I was also curious if you meant just change to ASCII or add some sort of detection to display the unicode version when available and ASCII when not.

**Comment by rashil2000** [comment]
Can something be done for the corner elements? They look out-of-place. The rest looks good.

> just change to ASCII

This one.

**Comment by ErykDarnowski** [comment]
Sure, give me a sec.

**Comment by rashil2000** [comment]
What happens if we keep using the previous elements for the corners? Does it still throw errors?

**Comment by ErykDarnowski** [comment]
In my case it doesn't print correctly instead of the corner it prints: â”

What about this version? I modified the . at the bottom:
![ASCII](https://user-images.githubusercontent.com/81530705/155531733-16325d07-41ea-4912-aa38-e5054d92a354.png)

**Comment by rashil2000** [comment]
The first one gives a rounded-corners vibe (which is quite uncharacteristic of the logo).

The second one increases the height in comparison to width, but we need it to be a square.

Hmm, let me investigate a bit more.

@HO-COOH do you have any suggestions?

**Comment by ErykDarnowski** [comment]
How about the widened third logo, the last one?

**Comment by rashil2000** [comment]
Can you try this one:
```
|‾‾‾‾‾|
|     |
|_____|
```

**Comment by ErykDarnowski** [comment]
Unfortunately, this is how it looks:
![ASCII](https://user-images.githubusercontent.com/81530705/155536234-f0b6b1ad-4c50-42d2-8fe9-76a9918eb390.png)

**Comment by rashil2000** [comment]
Can you try changing your output encoding as described here - https://github.com/kiedtl/winfetch/pull/126#issuecomment-1046016403

There are more details in that thread that might help.

**Comment by ErykDarnowski** [comment]
Weird, I managed to set my $OutputEncoding to UTF8 but the logo still looks like this:
[ASCII](https://user-images.githubusercontent.com/81530705/155536234-f0b6b1ad-4c50-42d2-8fe9-76a9918eb390.png)
Should I restart my computer?

**Comment by rashil2000** [comment]
Can you try these steps here and restart the computer:

https://www.windowsphoneinfo.com/threads/some-unicode-characters-suddenly-not-displaying-properly-in-every-program-windows-10.557285/#post-2619733

![image](https://user-images.githubusercontent.com/46838874/155540300-6eac1ccc-358d-44d9-ad22-9c00d72a0c6a.png)

**Comment by ErykDarnowski** [comment]
Yup, that solved it. But by accident I have found out that if the uptime is less than 1 minute, winfetch just leaves a blank space!

**Comment by rashil2000** [comment]
Hmm that's because we start counting the lowest unit as a minute. I think it fits most use cases.

**Comment by ErykDarnowski** [comment]
Okay, this is how the logo looks now:
![ASCII](https://user-images.githubusercontent.com/81530705/155543775-b888cbca-2dbf-479a-93f0-2da23f5ff188.png)

**Comment by rashil2000** [comment]
I think the old logo will work too, now. No change needed. Can you test it?

**Comment by ErykDarnowski** [comment]
Yup, after changing settings the old, 100% unicode version of the logo also works for me:
![ASCII](https://user-images.githubusercontent.com/81530705/155544776-bb7a25c6-e799-4b84-8eec-b3d5641d4f82.png)

**Comment by rashil2000** [comment]
Nice!

We can mention the steps in the above comment in the Wiki, in case someone else faces the same problem.

So this issue can be closed now?

**Comment by ErykDarnowski** [comment]
Sure! Mentioning this in the Wiki will definitely help with the confusion. Thank you for everything!

**Comment by rashil2000** [comment]
No worries, you're welcome.

Note that the display resolution part is getting refactored, which will enable us to show refresh rates too. See https://github.com/kiedtl/winfetch/pull/126#issuecomment-1030116001.

**Comment by HO-COOH** [comment]
> Can you try these steps here and restart the computer:
> 
> https://www.windowsphoneinfo.com/threads/some-unicode-characters-suddenly-not-displaying-properly-in-every-program-windows-10.557285/#post-2619733
> 
> ![image](https://user-images.githubusercontent.com/46838874/155540300-6eac1ccc-358d-44d9-ad22-9c00d72a0c6a.png)

Thanks for this piece of info 👍 , my issue in #126  is solved. I suggest this could be put in readme or something.

**Comment by rashil2000** [comment]
Will update the Wiki (when the feature is released).
