### ISSUE TITLE
MaxClockSpeed for info_cpu() adds redundant trailing spaces to cpu.name

### ISSUE THREAD

**Issue by xtonousou** [kiedtl/winfetch#147]
Im using winfetch as of this commit e5cd798a62b8eacf2ee8815b9a2106a3800a2cce

Noticed that there are trailing spaces on cpu.name as you can see:

![image](https://user-images.githubusercontent.com/9947828/187049699-54eb8c92-46f0-4277-8552-749c34338aca.png)

The solution is to use `Trim()` as below:
```powershell
function info_cpu {
    $cpu = Get-CimInstance -ClassName Win32_Processor -Property Name,MaxClockSpeed -CimSession $cimSession
    $cpuname = if ($cpu.Name.Contains('@')) {
        ($cpu.Name -Split ' @ ')[0]
    } else {
        $cpu.Name
    }
    $cpuname = $cpuname.Trim()
    $cpufreq = [math]::round((([int]$cpu.MaxClockSpeed)/1000), 2)
    return @{
        title   = "CPU"
        content = "${cpuname} @ ${cpufreq}GHz"
    }
}
```

After patch:

![image](https://user-images.githubusercontent.com/9947828/187049735-590a4180-f439-40aa-a5ef-871a51ae3e91.png)

**Comment by rashil2000** [comment]
Please make a PR for the fix!

**Comment by xtonousou** [comment]
PR here #148 ready for review and merge.
