### ISSUE TITLE
NoProcessFoundForGivenID

### ISSUE THREAD

**Issue by napzero** [kiedtl/winfetch#72]
Hi, I'm seeing this error. It only happens when I run it from a particular launcher script, so sorry for the weirdness. I've tried various ways to get around it. 

![Screen Shot 2021-03-24 at 11 22 03 AM](https://user-images.githubusercontent.com/19921477/112531435-8fe87b80-8d75-11eb-8ccd-650bdd0a6314.png)

Here is some more info from the environment in the launcher:
![Screen Shot 2021-04-06 at 12 53 19 PM](https://user-images.githubusercontent.com/19921477/113756733-5f8ad080-96d7-11eb-8c44-0c87dd080ecd.png)

**Comment by rashil2000** [comment]
It looks like the parent process that called the script has exited/was killed. Can you confirm this with PowerShell Core?

**Comment by napzero** [comment]
How would I do that? Sorry I'm still a bit of a PS n00b.

**Comment by rashil2000** [comment]
Install the new version of PowerShell (version 7), you can use the Store to install it (don't worry, it won't overwrite your existing PowerShell). Then test your script there.

**Comment by napzero** [comment]
Sure enough, I was running the script with the cmd command 'start' which spins off the PS and exits, causing the error.
I was using it for it's /max parameter, which makes the new window fullscreen.
Looking for an alternate solution now...
Thanks

**Comment by napzero** [comment]
I thought it was just the start command. 
The error doesn't happen in PS Core, but still happens in standard PS 5.

**Comment by rashil2000** [comment]
That's strange, are you sure you're following the exact same procedure for both Windows PowerShell and PowerShell Core? 

Do you mind sharing the script that starts winfetch? I'd like to test it locally.

Make sure to remove any personally identifiable information from it.

**Comment by napzero** [comment]
I've pinpointed it. It's because I tend to start my admin shells using the attached batch file. It contains a 'start' in it, so yes the original process does exit, but I find it odd that this 'spun off' process would bother the PowerShell command like that. 

I wrote this back in the Windows 7 days when there wasn't a built-in keyboard command to start an elevated shell. It's stuck with me due to habit. Might be time to change, but I'm still curious why the PS command is like this, since it is running from a cmd shell after all.

[cmda.zip](https://github.com/lptstr/winfetch/files/6288139/cmda.zip)

**Comment by rashil2000** [comment]
Hmm, I don't have much experience with Batchfile, so can't really say. This is indeed a peculiar case. 

I have also observed similar behavior when PowerShell is launched inside Msys2 (using Mintty).

**Comment by napzero** [comment]
I can confirm it's not limited to batch files. If I run PS Core from the start menu and run Winfetch, it's ok, but if I then kill Explorer.exe, the error happens. 

Interestingly, the same does not happen if I run it in the Windows Terminal (from the MS Store). Winfetch runs fine after killing Explorer. 

They are both Store apps, so its a mystery to me why one is affected by Explorer dying and the other isn't. The one difference I can see is that in PS Core, Winfetch displays the Terminal as 'Windows Console', while in Terminal it displays 'Windows Terminal'.

**Comment by rashil2000** [comment]
I think you might be getting confused between a _shell_ and a _terminal_. Read [this](https://www.hanselman.com/blog/whats-the-difference-between-a-console-a-terminal-and-a-shell) awesome blog by @shanselman to clear any confusion up. 

The explanation for the problem you described above is pretty simple. The Windows Console (also known as `conhost.exe`) is the default terminal that ships with Windows. Killing Explorer would make conhost an orphan in this case (because you launched it from the Start Menu, its parent is actually Explorer). winfetch will give error in any case here, regardless of whether you're using Windows PowerShell or PowerShell Core.

As for Windows Terminal (`wt.exe`), for any shell launched within it (Command Prompt, Windows PowerShell, PowerShell Core etc.) will have the parent process as Windows Terminal itself, so both Windows PowerShell or PowerShell Core will run winfetch without any errors.

**Comment by napzero** [comment]
Thanks for the article, it did help clear up some things.

For the purposes of Winfetch though, could we perhaps put in a catch for this error, so despite running as an orphan process, it can at least look ok?

**Comment by rashil2000** [comment]
That's a good idea. Would you like to send a PR? It's really simple, and we are here to help :)

**Comment by napzero** [comment]
A what?

**Comment by napzero** [comment]
Sure. What do I need to do?

**Comment by rashil2000** [comment]
Try looking for `try...catch` instances in the code (one good example is IP address section), and wrap the terminal detection code in a similar instance.

**Comment by rashil2000** [comment]
Closed in ae576e07d569f8574629110f023efaa265408c91
