### ISSUE TITLE
Update Winfetch's Scoop manifest to not suggest Imagemagick

### ISSUE THREAD

**Issue by kiedtl** [kiedtl/winfetch#77]
I see that the Imagemagick dependency was removed -- kudos for that!

When a new release is made, [this line](https://github.com/lukesampson/scoop-extras/blob/247e29498e478dbdbfad3e81ba7c217d4b8fc5d0/bucket/winfetch.json#L7) in `scoop-extras`'s Winfetch manifest will have to be updated.

**Comment by rashil2000** [comment]
Will do the needful, thanks!
