### ISSUE TITLE
Show WinGet and just-install packages

### ISSUE THREAD

**Issue by Rioluuu** [kiedtl/winfetch#83]
Right now winfetch only shows packages which are installed from Chocolatey or Scoop. I think it would also be a good idea to show all the WinGet packages in winfetch.

In WinGet you can view the list of installed packages/apps using `winget list`.

**Comment by kiedtl** [comment]
[just-install](https://github.com/just-install/just-install) might also be a future goal.

**Comment by rashil2000** [comment]
winget package count can be calculated by

```
(winget list | Measure-Object).Count - 4
```

But the tricky part is that this counts all packages ever installed, not just those installed by winget itself. winget-only list is being tracked here microsoft/winget-cli#964.

**Comment by Rioluuu** [comment]
To be honest, I'd like to see all packages ever installed. It's also WinGets goal to import all the "packages" which were originally installed the "classical way".

**Comment by rashil2000** [comment]
We can have a flag to chose either behavior
