### ISSUE TITLE
Smaller logo version?

### ISSUE THREAD

**Issue by amithiel** [kiedtl/winfetch#86]
Hi there! I use neofetch on linux boxes, and i always use the smaller logo variants (less space needed).
I wonder if you have something similar here?

this is currently my config: 

![image](https://user-images.githubusercontent.com/848214/122639806-e60a5800-d0f3-11eb-824b-f3e7528580e1.png)

as you can see, a smaller logo would fit like a charm :)

**Comment by rashil2000** [comment]
Hmm, not exactly the same thing, but just today I was thinking about allowing custom ascii images. By default winfetch will have only 2-3 logos inside. 

Neofetch allows you to specify text files with any logo inside, so this seems like a reasonable request.

This will take some time, in the meanwhile you can use [bfetch](https://github.com/rashil2000/bfetch) (and tell me if it's missing anything 😅).

**Comment by kiedtl** [comment]
We could just use Windows 11's logo -- it seems like the sort of thing that's easy to make really small.
