### ISSUE TITLE
Custom ASCII art support

### ISSUE THREAD

**Issue by Fr-gs** [kiedtl/winfetch#95]
How can I get custom ascii art?
I have been able to use images but I don't know how I can do this with text

**Comment by rashil2000** [comment]
Not possible currently. Would you like to work on it?

**Comment by Fr-gs** [comment]
> 
> 
> Not possible currently. Would you like to work on it?

I would if I knew anything about programming

**Comment by Fr-gs** [comment]
Do you know if it will be possible?

**Comment by rashil2000** [comment]
You'll need to know PowerShell 😅

**Comment by Codevarg** [comment]
idk how usefull it will be but i found a interesting shell script on reddit made years ago that converts images to ASCII text

full credit to the creator: https://www.reddit.com/r/PowerShell/comments/2hxam7/print_images_to_the_console_as_colored_text/

**Comment by rashil2000** [comment]
Wow, amazing find!

**Comment by Codevarg** [comment]
> Wow, amazing find!

Cheers! hope it will be useful to the project and help resolve this issue!

**Comment by iieuphoria** [comment]
> You can replace the default ASCII art from [winfetch.ps1](https://github.com/kiedtl/winfetch/blob/master/winfetch.ps1) with the one you like. ![image](https://user-images.githubusercontent.com/71691514/136597388-d2bb959e-1cc3-45a6-906b-c694ffd5b4c6.png)

ive been trying to do this but all my ascii images are well too wide and cover the information column

**Comment by rashil2000** [comment]
ASCII support will come in the next release. You can try running linked PR if you want.
